events {}

http {
    server {
        listen 80;

        server_name back.valinorfa.ir;

        location /.well-known/acme-challenge/ {
            alias /var/www/certbot/.well-known/acme-challenge/;
        }

        location / {
            proxy_pass http://taskflow-web-1:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

        }
    }
}