version = 5.6.0
archive_dir = /etc/letsencrypt/archive/back.valinorfa.ir
cert = /etc/letsencrypt/live/back.valinorfa.ir/cert.pem
privkey = /etc/letsencrypt/live/back.valinorfa.ir/privkey.pem
chain = /etc/letsencrypt/live/back.valinorfa.ir/chain.pem
fullchain = /etc/letsencrypt/live/back.valinorfa.ir/fullchain.pem
[renewalparams]
account = 98d68ee1b8b33943ddb8a3ccb767487e
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
back.valinorfa.ir = /var/www/certbot
